FROM node:20-slim

WORKDIR /app

# copy dependency（cache layer）
COPY package*.json ./

RUN npm install

# copy source code
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "--port", "5173"]